/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as RegisterRouteImport } from "./pages/register"
import { Route as LoginRouteImport } from "./pages/login"
import { Route as EmailConfirmationRouteImport } from "./pages/email-confirmation"
import { Route as AnimeRouteImport } from "./pages/anime"
import { Route as AuthenticatedRouteRouteImport } from "./pages/_authenticated/route"
import { Route as IndexRouteImport } from "./pages/index"
import { Route as AuthenticatedProfileRouteImport } from "./pages/_authenticated/profile"

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfirmationRoute = EmailConfirmationRouteImport.update({
  id: "/email-confirmation",
  path: "/email-confirmation",
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: "/anime",
  path: "/anime",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/anime": typeof AnimeRoute
  "/email-confirmation": typeof EmailConfirmationRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/profile": typeof AuthenticatedProfileRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/anime": typeof AnimeRoute
  "/email-confirmation": typeof EmailConfirmationRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/profile": typeof AuthenticatedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren
  "/anime": typeof AnimeRoute
  "/email-confirmation": typeof EmailConfirmationRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/_authenticated/profile": typeof AuthenticatedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/anime"
    | "/email-confirmation"
    | "/login"
    | "/register"
    | "/profile"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/anime"
    | "/email-confirmation"
    | "/login"
    | "/register"
    | "/profile"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/anime"
    | "/email-confirmation"
    | "/login"
    | "/register"
    | "/_authenticated/profile"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnimeRoute: typeof AnimeRoute
  EmailConfirmationRoute: typeof EmailConfirmationRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/email-confirmation": {
      id: "/email-confirmation"
      path: "/email-confirmation"
      fullPath: "/email-confirmation"
      preLoaderRoute: typeof EmailConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/anime": {
      id: "/anime"
      path: "/anime"
      fullPath: "/anime"
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/profile": {
      id: "/_authenticated/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnimeRoute: AnimeRoute,
  EmailConfirmationRoute: EmailConfirmationRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
