/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as AnimeRouteRouteImport } from "./pages/anime/route"
import { Route as AuthenticatedRouteRouteImport } from "./pages/_authenticated/route"
import { Route as IndexRouteImport } from "./pages/index"
import { Route as AnimeIndexRouteImport } from "./pages/anime/index"
import { Route as AuthResetPasswordRouteImport } from "./pages/auth/reset-password"
import { Route as AuthRegisterRouteImport } from "./pages/auth/register"
import { Route as AuthLoginRouteImport } from "./pages/auth/login"
import { Route as AuthForgotPasswordRouteImport } from "./pages/auth/forgot-password"
import { Route as AuthEmailConfirmationRouteImport } from "./pages/auth/email-confirmation"
import { Route as AnimeIdRouteImport } from "./pages/anime/$id"
import { Route as AuthenticatedProfileRouteImport } from "./pages/_authenticated/profile"

const AnimeRouteRoute = AnimeRouteRouteImport.update({
  id: "/anime",
  path: "/anime",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AnimeRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/auth/reset-password",
  path: "/auth/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/auth/register",
  path: "/auth/register",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/auth/forgot-password",
  path: "/auth/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailConfirmationRoute = AuthEmailConfirmationRouteImport.update({
  id: "/auth/email-confirmation",
  path: "/auth/email-confirmation",
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => AnimeRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/anime": typeof AnimeRouteRouteWithChildren
  "/profile": typeof AuthenticatedProfileRoute
  "/anime/$id": typeof AnimeIdRoute
  "/auth/email-confirmation": typeof AuthEmailConfirmationRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/anime/": typeof AnimeIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/anime/$id": typeof AnimeIdRoute
  "/auth/email-confirmation": typeof AuthEmailConfirmationRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/anime": typeof AnimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren
  "/anime": typeof AnimeRouteRouteWithChildren
  "/_authenticated/profile": typeof AuthenticatedProfileRoute
  "/anime/$id": typeof AnimeIdRoute
  "/auth/email-confirmation": typeof AuthEmailConfirmationRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/anime/": typeof AnimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/anime"
    | "/profile"
    | "/anime/$id"
    | "/auth/email-confirmation"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/anime/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/profile"
    | "/anime/$id"
    | "/auth/email-confirmation"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/anime"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/anime"
    | "/_authenticated/profile"
    | "/anime/$id"
    | "/auth/email-confirmation"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/anime/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnimeRouteRoute: typeof AnimeRouteRouteWithChildren
  AuthEmailConfirmationRoute: typeof AuthEmailConfirmationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/anime": {
      id: "/anime"
      path: "/anime"
      fullPath: "/anime"
      preLoaderRoute: typeof AnimeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/anime/": {
      id: "/anime/"
      path: "/"
      fullPath: "/anime/"
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof AnimeRouteRoute
    }
    "/auth/reset-password": {
      id: "/auth/reset-password"
      path: "/auth/reset-password"
      fullPath: "/auth/reset-password"
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/register": {
      id: "/auth/register"
      path: "/auth/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/auth/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/forgot-password": {
      id: "/auth/forgot-password"
      path: "/auth/forgot-password"
      fullPath: "/auth/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/email-confirmation": {
      id: "/auth/email-confirmation"
      path: "/auth/email-confirmation"
      fullPath: "/auth/email-confirmation"
      preLoaderRoute: typeof AuthEmailConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/anime/$id": {
      id: "/anime/$id"
      path: "/$id"
      fullPath: "/anime/$id"
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof AnimeRouteRoute
    }
    "/_authenticated/profile": {
      id: "/_authenticated/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AnimeRouteRouteChildren {
  AnimeIdRoute: typeof AnimeIdRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
}

const AnimeRouteRouteChildren: AnimeRouteRouteChildren = {
  AnimeIdRoute: AnimeIdRoute,
  AnimeIndexRoute: AnimeIndexRoute,
}

const AnimeRouteRouteWithChildren = AnimeRouteRoute._addFileChildren(
  AnimeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnimeRouteRoute: AnimeRouteRouteWithChildren,
  AuthEmailConfirmationRoute: AuthEmailConfirmationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
